### ISSUE TITLE
ami test run error log. 

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#1]
Following command raises run-time exception error. 

>ami-search-cooccur --project <CProject> country drugs species

Changing the command-line to 

>ami-search-cooccur <CProject> country drugs species

runs properly.  Is --project argument for ami2 tools ? why it raises java run-time exception with ami tools?

**Comment by petermr** [comment]
Thanks very much!
This is exactly how we should report errors.

`ami-search` is not yet under the new `picocli` commandline system. `--project` always requires an argument. I am interested that the second line actually works.

When you report an error please give the stacktrace. "Raises an error" could be `FileNotFoundException` or completely different. (BTW the Java term is "throws an Exception");

Can you put a brief account of what you actually ran and worked, and what the output was. (Snip if necessary). That will be very helpful.
