### ISSUE TITLE
Maximize command prompt on Windows

### ISSUE THREAD

**Issue by ay-amityadav** [petermr/tigr2ess#15]
Not able to maximize the Command prompt to full screen on Windows systems is a common problem.
Following are some links in this regard:
[https://www.thewindowsclub.com/full-screen-command-prompt-in-windows-7](https://www.thewindowsclub.com/full-screen-command-prompt-in-windows-7)
[https://www.wikihow.com/Fix-Full-Screen-Command-Prompt](https://www.wikihow.com/Fix-Full-Screen-Command-Prompt)

Thanks @petermr for suggesting [http://cmder.net/](http://cmder.net/).

This needs standardizing.

**Comment by petermr** [comment]
We should create sub directories for Unix Mac Windows and put this information there.
