### ISSUE TITLE
Local dictionary usage for co-occurrence search. 

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#16]

**Comment by ambarishK** [comment]
Sir, would you mention how to use local dictionary to get co-occurrence results?

**Comment by ambarishK** [comment]
As I find co-occurrences are being searched without using dictionary which we have created.

**Comment by petermr** [comment]
```
ami-seach-cooccur <project> <dictionary>, [<dictionary>]]
```
where `<dictionary>` is
  * EITHER a builtin dictionary (country, drugs, pesticides ...)
  * OR a fully-qualifed local filename (e.g. `/Users/pm286/ContentMine/dictionaries/crops/cowpea.xml`)

We will expect users to download the dictionaries locally from Github.
