### ISSUE TITLE
ami-dictionary translate

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#17]

**Comment by ambarishK** [comment]
ami-dictionaries translate --input /home/ambarish123/rice.xml --outformats JSON  
sir, please correct the command. It raises java null pointer exception.

**Comment by petermr** [comment]
You must give the stack trace. and all the output.
Does the file exist?
the outformats may be case-sensitive, Can you check that there wasn't a parsing error (normally in red)

**Comment by petermr** [comment]
I ran:
```
ami-dictionaries --outformats JSON
```
and got the output:
```
Invalid value for option '--outformats' at index 0 (output format): expected one of [xml, html, json] (case-sensitive) but was 'JSON'
```
can you check that you got this error.
Also the output gives:
```
Specific values (AMIDictionaryTool)
================================
dataCols      null
dictionary    null
dictionaryTop     null
href          null
hrefCols      null
input         null
informat      null
dictInformat  null
linkCol       null
log4j         null
nameCol       null
operation     help
outformats    [xml]
splitCol      ,
termCol       null
terms         null
```
so you can see the outformats are set to the default (xml). Actually I think we should have no default so I will reset this to null.

**Comment by petermr** [comment]
I believe this is because currently `directory` is a mandatory option for `translate`. I will fix this.
