### ISSUE TITLE
ami-species test run.

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#3]
Sir, all output of the ami-species search is into XML file format. Is it possible to get HTML file format output?

**Comment by ambarishK** [comment]
**### run-time log msg**

0	[main] DEBUG org.contentmine.norma.NormaArgProcessor  - CREATING CTree FROM INPUT:[scholarly-html]; FIX THIS, BAD STRATEGY

Can it be fixed? Does it impact the output results?

**Comment by petermr** [comment]
(suggest you split this into 2 issues).
(A) Sir, all output of the ami-species search is into XML file format. Is it possible to get HTML file format output?
Yes - I may create HTML later. This would give snippets on a per-hit basis.
(B) What was the command?
