### ISSUE TITLE
Dictionary_creation_Indian_research_institutes.

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#35]
ambarish123@ubuntu:~$ ami-dictionary create --input https://en.wikipedia.org/wiki/Department_of_Science_and_Technology_(India) --informat wikipage --dictionary Research_institute7 --outformats xml
bash: syntax error near unexpected token `('

#### web-link contains '(', which is not readable into the command-line. Please resolve.

**Comment by petermr** [comment]
Please:
* reformat with &lt;pre> tags (monospace)
* change the title.

A good title would be
```
URLs which contain punctuation (parentheses) must be escaped
```

**Comment by petermr** [comment]
```
$ ami-dictionary create --input https://en.wikipedia.org/wiki/Department_of_Science_and_Technology_(India) \
 --informat wikipage --dictionary Research_institute7 --outformats xml
bash: syntax error near unexpected token `('
```

I quoted as follows:
```
$ ami-dictionary create \
--input 'https://en.wikipedia.org/wiki/Department_of_Science_and_Technology_(India)'  \
 --informat wikipage --dictionary Research_institute7 --outformats xml
```
Note second line. The quotes are round the value.
It ran without errors (though the result is not a very useful dictionary).

DOCUMENTATION NEEDED
