### ISSUE TITLE
ami20190216 testrun and bibliographic info.

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#38]
Sir, test run for the new release - ami20190216 is successful.

How to fetch bibliographic information? Would you please hint for the syntax?

**Comment by petermr** [comment]
Good to know.
I am taking the bibliographic info from `eupmc_results.json` created by `getpapers`. I have previously written a parser for this and a typical entry can include many or all of the following:
```
	public static final String HEAD_ABSTRACT        = "Abstract";
	public static final String HEAD_AUTHOR_LIST     = "AuthorList";
	public static final String HEAD_COPYRIGHT       = "Copyright";
	public static final String HEAD_CROSSREF_MD     = "CrossrefMD";
	public static final String HEAD_DATE            = "Date";
	public static final String HEAD_DESCRIPTION     = "Description";
	public static final String HEAD_DOI             = "DOI";
	public static final String HEAD_DOWNLOADED_HTML = "HTMLFile";
	public static final String HEAD_DOWNLOADED_PDF  = "PDFFile";
	public static final String HEAD_DOWNLOADED_XML  = "XMLFile";
	public static final String HEAD_FIRST_PAGE      = "FirstPage";
	public static final String HEAD_HTMLURL         = "HTMLURL";
	public static final String HEAD_ISSN            = "ISSN";
	public static final String HEAD_ISSUE           = "Issue";
	public static final String HEAD_JOURNAL         = "Journal";
	public static final String HEAD_KEYWORDS        = "Keywords";
	public static final String HEAD_LICENSE         = "License";
	public static final String HEAD_LINKS           = "Links";
	public static final String HEAD_PDFURL          = "PDFURL";
	public static final String HEAD_PREFIX          = "Prefix";
	public static final String HEAD_PUBLISHER       = "Publisher";
	public static final String HEAD_PUBLISHER_MD    = "PublisherMD";
	public static final String HEAD_QUICKSCRAPE_MD  = "QuickscrapeMD";
	public static final String HEAD_TITLE           = "Title";
	public static final String HEAD_TYPE            = "Type";
	public static final String HEAD_URL             = "URL";
	public static final String HEAD_VOLUME          = "Volume";
	public static final String HEAD_XMLURL          = "XMLURL";
```
The question is how much of this do delegates want and how to display it in a rich fashion.

**Comment by petermr** [comment]
Now committed to latest jar file. 

<pre>
articles | bibliography | dic:country | word:frequencies
-- | -- | -- | --
PMC2640145 local | New vectors of Rift Valley fev
                                  Fontenille D, T
                                   After an outbreak of Rift Vall | Mauritania South Africa, |  
PMC3167654 local | Emerging viral threats in Gabo 
                                 Bourgarel M, Wa
                                 Emerging infectious diseases ( |   | zygotes x 44 signal x 24 early x 23 pronuclei x 21 maternal x 23
</pre>

There are three fields of text (usually truncated), separated by break which are:
  * title
  * authorString
  * abstract
