### ISSUE TITLE
Dictionary creation from wikimedia link.

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#39]
Sir, is it possible to create dictionary from the wikimedia link, like https://commons.wikimedia.org/wiki/Category:Ocimum??

Please comment.

**Comment by petermr** [comment]
Excellent idea.
Note that this is Wiki*m*edia Commons, not Wikipedia or Wikidata. Commons is a large and valuable collection of other resources, such as images and videos. They will be valuable for reference and education, but not immediately for searching (the main point of current dictionaries).
Let's see what the delegates think.

**Comment by ambarishK** [comment]
Thank you so much sir.
