### ISSUE TITLE
ami-clean command-line help.

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#44]
ambarish123@ubuntu:~$ ami-clean -p /home/ambarish123/riceOROryza/ --file /home/ambarish123/riceOROryza/word.frequencies.count.xml

### Sir, I tried running the ami-clean tool using above options but run does not work and file persists. Please suggest.

**Comment by petermr** [comment]
Please report this in a detailed manner.
 * what did you do?
 * what happened?
   - did it crash?
   - did it exit prematurely?
   - did it give the wrong answers?
   - did it give a report?

Please attach any output.

Please rewrite the issue.


"does not work" gives no

**Comment by ambarishK** [comment]
##     * what did you do?
I tried to delete word.frequencies.count.xml from the CProject folder  -  riceOROryza/

##    * what happened?

It could not delete the passed-on file as input for --file command-line option. It generated Generic values and Specific values but could not proceed ahead for deletion of the file.

## * Snapshot of the error.

```
ambarish123@ubuntu:~$ ami-clean -p /home/ambarish123/RiceOROryza/ --file /home/ambarish123/RiceOROryza/gene.human.count.xml 

Generic values (AMICleanTool)
================================
basename            null
cproject            /home/ambarish123/RiceOROryza
ctree               
cTreeList           [/home/ambarish123/RiceOROryza/PMC5991738, /home/ambarish123/RiceOROryza/PMC6173730, /home/ambarish123/RiceOROryza/PMC6213974, /home/ambarish123/RiceOROryza/PMC6222575, /home/ambarish123/RiceOROryza/PMC6249995, /home/ambarish123/RiceOROryza/PMC6278296, /home/ambarish123/RiceOROryza/PMC6311050, /home/ambarish123/RiceOROryza/PMC6339128, /home/ambarish123/RiceOROryza/PMC6339371, /home/ambarish123/RiceOROryza/PMC6357162]
dryrun              false
excludeBase         null
excludeTrees        null
file types          []
forceMake           false
includeBase         null
includeTrees        null
log4j               
logfile             null
verbose             0

Specific values (AMICleanTool)
================================
files         [/home/ambarish123/RiceOROryza/gene.human.count.xml]
fileGlobs     []
dirs          []
dirGlobs      []
ambarish123@ubuntu:~$ cd RiceOROryza/
ambarish123@ubuntu:~/RiceOROryza$ ls
eupmc_fulltext_html_urls.txt  search.country.count.xml
eupmc_results.json            search.country.documents.xml
gene.human.count.xml          search.country.snippets.xml
gene.human.documents.xml      search.drugs.count.xml
gene.human.snippets.xml       search.drugs.documents.xml
```
Please go through it. File persists into CProject directory.

**Comment by petermr** [comment]
Generally well reported, thanks. BUT please quote ALL in-text filenames and commands with single backticks.

It could not delete the passed-on file as input for --file command-line option. It generated Generic values and Specific values but could not proceed ahead for deletion of the file.

should be

It could not delete the passed-on file as input for `--file` command-line option. It generated Generic values and Specific values but could not proceed ahead for deletion of the file.

I don't have access to this directory but I will try to replicate on my own.
Is it critical for the workshop?
Do we ask delegates to use ami-clean?
If not, we'll lower the priority.
