### ISSUE TITLE
getpapers installation on Windows 7 (32 bit) - minor edits required

### ISSUE THREAD

**Issue by ay-amityadav** [petermr/tigr2ess#51]
Operating System: Windows 7 (32 bit)

The installation steps were followed from [contentmine/getpapers](https://github.com/contentmine/getpapers), which in turn refers to [blahah/installing-node-tools](https://github.com/blahah/installing-node-tools) for the initial steps.

Step 1: Installing nodeJS. From the [downloads page](https://github.com/coreybutler/nvm-windows/releases), the latest version `nvm-setup.zip` is downloaded. The latest version is `1.1.7`. The file is uzipped and the included installer is run. This step runs smoothly.

Step 2: Installing node. This is done by running `nvm install 7`. The output for this is:
```
C:\Users\amit>nvm install 7
Downloading node.js version 7.10.1 (64-bit)...
Complete
Creating C:\Users\gold\Desktop\nvm\temp

Downloading npm version 4.2.0... Complete
Installing npm v4.2.0...

Installation complete. If you want to use this version, type

nvm use 7.10.1
```
**Note** Above it says: `Downloading node.js version 7.10.1 (64-bit)...`, so it means it's not able to figure out it's a 32-bit machine.

Step3: Next, we issue the command `nvm use 7.10.1`, and it runs smoothly.
Step4: Installing getpapers. We issue the command `npm install --global getpapers`, and the following error message is produced.
```
:npm install --global getpapers
This version of C:\Program Files\nodejs\node.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
This version of C:\Program Files\nodejs\node.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
```
As it is evident from above **Note**, we have installed npm for 64-bit machine, whereas our machine is 32-bit. Fortunately, nvm allows us to specify whether we wan't to install npm for 32-bit or 64-bit. Among a few possibilites, the command `nvm install 7 32` works. So in step2, we issue the command `nvm install 7 32` **instead of** `nvm install 7`. Here is how the output message looks:
```
:nvm install 7 32
Downloading node.js version 7.10.1 (32-bit)...
Complete
Creating C:\Users\gold\Desktop\nvm\temp

Downloading npm version 4.2.0... Complete
Installing npm v4.2.0...

Installation complete. If you want to use this version, type

nvm use 7.10.1
```
This also affects **Step3**, where we issue the command `nvm use 7.10.1 32`  **instead of** `nvm use 7.10.1`.

After the above changes, the command `npm install --global getpapers` successfully installs getpapers on the system.

**Comment by petermr** [comment]
Well done!
I have added this to the Installation instructions and pointed to the Github issues.
Please add all such problems to the installation directory.
