### ISSUE TITLE
standard Ocimum CProject

### ISSUE THREAD

**Issue by petermr** [petermr/tigr2ess#53]
We need exactly ONE Ocimum project in the tigr2ess/ directory. This project should be used for all tasks involving Ocimum. If there are a few problematic files (too large, too many species) we can remove them.
This file will be about 200 CTrees which is enough to give some good results but doesn't take too long to run.
I have one called osanctum200 which I will commit.

**Comment by ambarishK** [comment]
Sir, I downloaded all 2000 Ocimum articles from EPMC and running search over it. I will prepare a literature survey over Ocimum for myself and will upload to the repository (if required).

**Comment by petermr** [comment]
2000 articles ISNT part of the morning workshop. It's not high priority. It's confusing us.
It is more important that everyone can:
 * document and tidy their session/directory
 * test the system.

**Comment by ambarishK** [comment]
sure sir.
