### ISSUE TITLE
`ami-clean` expected behaviour

### ISSUE THREAD

**Issue by ay-amityadav** [petermr/tigr2ess#58]
At present, `ami-clean` is expected to delete files and folders inside a project. 

**With regard to workshop**
The possible case scenario I can think of using `ami-clean` is:
In the beginning, we have the `oscanctum200` project directory, we do a `ami-search osanctum200 dictionary_name1` on it, this creates data tables, cooccurence directory and other things. Once we have visualized this results for the above command, we would like to run `ami-search oscanctum200 dictionary_name2`, this time I expect to contain no files from the previous run (yes some files will be updated such as all the dataTables), but files specific such as `search.dictionary1.count.xml`, `search_dictionary2.snippets.xml` etc will still be present. 
It's a bit of source of confusion for what actually happened.

*For the moment we can keep it at low-priority.*

*Possible solution*: we design `ami-clean` in such a way that just issuing `ami-clean` clears the project of all the files created from the previous run of `ami-search`. OR we somehow call `ami-clean` internally from `ami-search` itself before its actual execution, this will save exectuing `ami-clean` between two `ami-search`.

Also, looking at `ami-clean` help output, it couldn't figure out how it could be more useful than the usual `rm` command for the **above case scenario**.

I request Peter to throw some light on this.

**Comment by petermr** [comment]
Leave open. 
I will try to fix ami-clean sometime.
