### ISSUE TITLE
ami installation failure on Windows 10

### ISSUE THREAD

**Issue by ay-amityadav** [petermr/tigr2ess#6]
Operating System: Windows 10 

The installation steps for `ami`  were followed from [normami/INSTALL.md](https://github.com/petermr/normami/blob/master/INSTALL.md) as referred by [tigr2ess/ami.md](https://github.com/petermr/tigr2ess/blob/master/ami.md).

Step1: The repository is cloned in directory `C:\Users\amit\Desktop\Tigr2ess`
Step2: The path `C:\Users\amit\Desktop\Tigr2ess\ami-jars-masters\ami-jars-masters\ami20190115\bin` is appended to the PATH variable. To confirm this, executing `echo %PATH%` at command prompt displays the following:
```
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\amit\AppData\Local\Microsoft\WindowsApps;C:\Users\amit\Desktop\Tigr2ess\ami-jars-master\ami-jars-master\ami20190115\bin
```

Step3: Running `ami-pdf` at command prompt produces the following error:
```
C:\Users\amit>ami-pdf
The input line is too long.
The syntax of the command is incorrect.
```

Not sure if this is the right place to raise this issue. Is it [petermr/normami](https://github.com/petermr/normami/issues)?

**Comment by ay-amityadav** [comment]
Working Solution:

On running `ami-pdf` at command prompt, the corresponding `ami-pdf.bat` file is executed. Every thing is fine until the line no 75 is reached, which is:
```
set CLASSPATH="%BASEDIR%"\etc;"%REPO%"\commons-cli-1.4.jar;"%REPO%"\cephis-0.1-SNAPSHOT.jar;"%REPO%"\junit-4.8.2.jar;"%REPO%"\commons-io-2.5.jar;"%REPO%"\log4j-1.2.16.jar;"%REPO%"\commons-lang3-3.0.jar;"%REPO%"\commons-math-2.2.jar;"%REPO%"\commons-csv-1.2.jar;"%REPO%"\joda-time-1.6.2.jar;"%REPO%"\xom-1.2.5.jar;"%REPO%"\xercesImpl-2.8.0.jar;"%REPO%"\xalan-2.7.0.jar;"%REPO%"\guava-18.0.jar;"%REPO%"\jtidy-4aug2000r7-dev.jar;"%REPO%"\tagsoup-1.2.jar;"%REPO%"\jsoup-1.9.2.jar;"%REPO%"\htmlunit-2.15.jar;"%REPO%"\commons-collections-3.2.1.jar;"%REPO%"\httpmime-4.3.3.jar;"%REPO%"\commons-codec-1.9.jar;"%REPO%"\htmlunit-core-js-2.15.jar;"%REPO%"\nekohtml-1.9.21.jar;"%REPO%"\cssparser-0.9.14.jar;"%REPO%"\sac-1.3.jar;"%REPO%"\commons-logging-1.1.3.jar;"%REPO%"\jetty-websocket-8.1.15.v20140411.jar;"%REPO%"\jetty-util-8.1.15.v20140411.jar;"%REPO%"\jetty-io-8.1.15.v20140411.jar;"%REPO%"\jetty-http-8.1.15.v20140411.jar;"%REPO%"\gson-2.8.2.jar;"%REPO%"\json-path-2.0.0.jar;"%REPO%"\slf4j-api-1.7.10.jar;"%REPO%"\json-smart-2.1.1.jar;"%REPO%"\asm-1.0.2.jar;"%REPO%"\asm-3.3.1.jar;"%REPO%"\pdfbox-2.0.11.jar;"%REPO%"\fontbox-2.0.11.jar;"%REPO%"\boofcv-core-0.32.jar;"%REPO%"\georegression-0.18.jar;"%REPO%"\ddogleg-0.15.2.jar;"%REPO%"\jsr305-3.0.2.jar;"%REPO%"\jsr250-api-1.0.jar;"%REPO%"\boofcv-calibration-0.32.jar;"%REPO%"\boofcv-feature-0.32.jar;"%REPO%"\boofcv-geo-0.32.jar;"%REPO%"\boofcv-io-0.32.jar;"%REPO%"\snakeyaml-1.23.jar;"%REPO%"\boofcv-ip-0.32.jar;"%REPO%"\boofcv-learning-0.32.jar;"%REPO%"\boofcv-recognition-0.32.jar;"%REPO%"\main-0.4.jar;"%REPO%"\models-0.4.jar;"%REPO%"\learning-0.4.jar;"%REPO%"\io-0.4.jar;"%REPO%"\protobuf-java-2.6.1.jar;"%REPO%"\jarchivelib-0.5.0.jar;"%REPO%"\commons-compress-1.7.jar;"%REPO%"\xz-1.4.jar;"%REPO%"\zip4j-1.3.2.jar;"%REPO%"\boofcv-sfm-0.32.jar;"%REPO%"\boofcv-swing-0.32.jar;"%REPO%"\rsyntaxtextarea-2.6.1.jar;"%REPO%"\imgscalr-lib-4.2.jar;"%REPO%"\jbig2-imageio-3.0.1.jar;"%REPO%"\ejml-all-0.37.1.jar;"%REPO%"\ejml-core-0.37.1.jar;"%REPO%"\ejml-fdense-0.37.1.jar;"%REPO%"\ejml-ddense-0.37.1.jar;"%REPO%"\ejml-cdense-0.37.1.jar;"%REPO%"\ejml-zdense-0.37.1.jar;"%REPO%"\ejml-dsparse-0.37.1.jar;"%REPO%"\ejml-simple-0.37.1.jar;"%REPO%"\Saxon-HE-9.6.0-3.jar;"%REPO%"\xmlunit-1.4.jar;"%REPO%"\xml-apis-1.4.01.jar;"%REPO%"\lucene-core-4.10.3.jar;"%REPO%"\lucene-analyzers-common-4.10.3.jar;"%REPO%"\univocity-parsers-1.5.6.jar;"%REPO%"\javax.ws.rs-api-2.1.jar;"%REPO%"\resteasy-client-3.6.1.Final.jar;"%REPO%"\jboss-jaxrs-api_2.1_spec-1.0.1.Final.jar;"%REPO%"\resteasy-jaxrs-3.6.1.Final.jar;"%REPO%"\jboss-jaxb-api_2.3_spec-1.0.0.Final.jar;"%REPO%"\reactive-streams-1.0.2.jar;"%REPO%"\validation-api-1.1.0.Final.jar;"%REPO%"\jboss-annotations-api_1.2_spec-1.0.0.Final.jar;"%REPO%"\activation-1.1.1.jar;"%REPO%"\jcip-annotations-1.0.jar;"%REPO%"\javax.json.bind-api-1.0.jar;"%REPO%"\jboss-logging-3.3.1.Final.jar;"%REPO%"\httpclient-4.5.4.jar;"%REPO%"\httpcore-4.4.7.jar;"%REPO%"\picocli-3.9.1.jar;"%REPO%"\normami-0.1-SNAPSHOT.jar
```

This line contains 2095 characters, which apparently exceeds the limit of having 2047 characters which can be entered at the command prompt.
https://support.microsoft.com/en-in/help/830473/command-prompt-cmd-exe-command-line-string-limitation

I tried running the script file after removing the above line, and the execution moves beyond this line and the above error message is not produced.
To overcome the above problem, the line `set CLASSPATH="%BASEDIR%"\etc;"%REP0%"\commons.......`line is replaced by just `set CLASSPATH="%BASEDIR%"\etc;"%REP0%"\*`, as per the link https://stackoverflow.com/questions/219585/including-all-the-jars-in-a-directory-within-the-java-classpath
Here, basically all the jar files present in the `.../repo` directory are added to the CLASSPATH (* acting as a regular expression to include all the files in the concerned directory), and this reduces the no of characters inputted at the command prompt below the maximum allowed limit.

**My Concern** is that this directory contains 113 jars, and the above original `set CLASSPATH....` includes/adds 94 .jar files from the `.../repo` directory. Can the addition of extra jar files to CLASSPATH result in any sort of problem?

After the above edit, running `ami-pdf` at the command prompt produces the following message:
```
C:\Users\amit>ami-pdf
'java' is not recognized as an internal or external command,
operable program or batch file.
```
So it seems java doesn't come inbuilt with Windows 10. So after installing Java from this link: https://www.java.com/en/download/ and running java at command prompt, the following message is outputted:
```
C:\Users\amit>java
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
............
..........
```
This confirms java is installed on the system.

Next, we run `ami-pdf`, and it produces the following result:
```
C:\Users\amit>ami-pdf
Usage: ami-pdf [OPTIONS]
Description
===========
Convert PDFs to SVG-Text, SVG-graphics and Images. Does not process images,
graphics or text.often followed by ami-image and ami-xml?
Options
=======
      --basename=<userBasename>
                            User's basename for outputfiles (e.g. foo/bar/<basename>.
                              png. By default this is computed by AMI. This allows
                              users to create their own variants, but they won't be
                              known by default to subsequentapplications
...............
..............
```
**Summary**
1. Java needs to be separately installed on Windows 10. (On ubuntu 16.04, it is already there, but we might have to be careful about other linux distros or versions)
2. I could not reach to the conclusion regarding what is the maximum allowed limit of characters at the command prompt on various windows versions, whether it is 2047 or 8191. But if my above **Concern** doesn't produce any ill-effects, then the above fix would work regardless of windows version. To confirm this, I would be trying running ami on other popular windows versions.

I request Peter and others to share their views on this.

**Comment by ambarishK** [comment]
same issue over Windows-08. I will consult you morning time.

**Comment by petermr** [comment]
Thank you.
This is useful research. Sorry I didn't catch this earlier
The commandline length is a known problem on Windows. 
I can't easily see how we can reduce the number of jars if we distribute as individual libraries. 
I'll have a think.
It's always possible to run the jar-with-dependencies but the CL is much messier.
I seem to remember there is a way of increasing the Windows CL to an arbitrarily large size, 
I think we should all try to solve this problem.

I have found:
https://stackoverflow.com/questions/2524714/appassembler-and-long-classpath/52585324#52585324
which addresses the precise problem and I'll try it out...

Is this still a problem 20190205?

**Comment by ay-amityadav** [comment]
I tried 20190205, and it also has the same problem.

**Comment by ay-amityadav** [comment]
Sorry, I tried 20190204, I suppose this is what is being meant here.
