### ISSUE TITLE
ami20190224 vs appassembler

### ISSUE THREAD

**Issue by ay-amityadav** [petermr/tigr2ess#82]
Please have a look at setting path for linux at https://github.com/petermr/tigr2ess/blob/master/installation/unix/set_path/set_path.md
I have added the path `export PATH="$PATH:$HOME/Desktop/ContentMine/software/ami20190224/bin`
(As per our discussion on etherpad).
Note above `ami20190224`. I just realized this is different from `$HOOME/Desktop/ContentMine/software/appassembler/bin` path defined in section `PATH for AMI` https://github.com/petermr/tigr2ess/blob/master/installation/INSTALLATION.md. 
 `appassembler` instead of `ami20190224` 

My mistake, I forgot about this, we discussed yesterday. Is it possible to stick with `ami20190224`?

**Comment by petermr** [comment]
Thanks,
Yes, we'll stick with `ami20190224`.

BTW you have `$HOOME` - just a local typo I assume :-)
